routes/dashboard.php
<?php
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        Route::prefix('cp')->name('cp.')->middleware(['auth'])->group(function () {
            Route::get('/','DashboardController@index')->name('index');
            //category routes
            Route::resource('categories', 'CategoryController')->except(['show']);
            Route::get('categories/delCat/{id}','CategoryController@destroy');
            Route::get('categoriesAll/delet_all_categories/{ids}','CategoryController@del_all');
            //product routes
            Route::resource('products', 'ProductController')->except(['show']);
            Route::get('products/delProduct/{id}','ProductController@destroy');
            Route::get('catProducts/{id}','ProductController@catProducts');
            Route::get('productsAll/delet_all_products/{ids}','ProductController@del_all');
            //client routes
            Route::resource('clients', 'ClientController')->except(['show']);
            Route::resource('clients.orders', 'ClientOrdersController')->except(['show']);
            Route::get('clients/delClient/{id}','ClientController@destroy');
            Route::get('clientsAll/delet_all_clients/{ids}','ClientController@del_all');
            //order routes
            Route::resource('orders', 'OrderController');
            Route::get('/orders/{order}/products', 'OrderController@products')->name('orders.products');
            Route::get('orders/delOrder/{id}','OrderController@destroy');
            
            //user routes
            Route::resource('users', 'UserController')->except(['show']);
            Route::get('users/delUser/{id}','UserController@destroy');
            Route::get('usersAll/delet_all_users/{ids}','UserController@del_all');
    
        });
    });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('cp.index');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    use \Dimsav\Translatable\Translatable;
    
    public $translatedAttributes = ['name'];
    public function products()
    {
        return $this->hasMany(Product::class);

    }//end of products

}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;    
use Illuminate\Validation\Rule;

class CategoryController extends Controller
{
    public function __construct()
    {
        //create read update delete
        $this->middleware(['permission:read_categories'])->only('index');
        $this->middleware(['permission:create_categories'])->only('create');
        $this->middleware(['permission:update_categories'])->only('edit');
        $this->middleware(['permission:delete_categories'])->only(['destroy','del_all']);

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cats=Category::orderBy('id','desc')->get();
        return view('dashboard.categories.index',compact('cats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [];

        foreach (config('translatable.locales') as $locale) {

            $rules += [$locale . '.name' => ['required', Rule::unique('category_translations', 'name')]];

        }//end of for each

        $request->validate($rules);

        Category::create($request->except('_token'));
        connectify('success', 'Done', __('site.added_successfully'));
		return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $rules = [];

        foreach (config('translatable.locales') as $locale) {

            $rules += [$locale . '.name' => ['required', Rule::unique('category_translations', 'name')->ignore($category->id, 'category_id')]];

        }//end of for each

        $request->validate($rules);
        $category->update($request->except(['_token','_method']));
        connectify('success', 'Done', __('site.updated_successfully'));
		return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category=Category::findOrFail($id);
        $category->delete();
        connectify('success', 'Done',  __('site.deleted_successfully'));
		return redirect()->back();
    }
    public function del_all($ids)
    {
        
        $cats_id = explode(',',$ids);
        foreach($cats_id as $id){
            $cat = Category::findOrFail($id);
            $del = $cat->delete();
        }       
        if($del)
            connectify('success', 'Done',  __('site.deleted_successfully'));
        else
            connectify('error', 'Error', 'Somthing Wrong Please Try again later');
		return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/ClientController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Client;
class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::orderBy('id','desc')->get();
        return view('dashboard.clients.index',compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'phone' => 'required|array|min:1',
            'phone.0' => 'required',
            'address' => 'required',
        ]);

        $request_data = $request->except('_token');
        $request_data['phone'] = array_filter($request->phone);

        Client::create($request_data);
        connectify('success', 'Done', __('site.added_successfully'));
		return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $request->validate([
            'name' => 'required',
            'phone' => 'required|array|min:1',
            'phone.0' => 'required',
            'address' => 'required',
        ]);

        $request_data = $request->except(['_token','_method']);
        $request_data['phone'] = array_filter($request->phone);

        $client->update($request_data);
        connectify('success', 'Done', __('site.updated_successfully'));
		return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::findOrFail($id);
        $client->delete();
        connectify('success', 'Done', __('site.deleted_successfully'));
		return redirect()->back();
    }
    public function del_all($ids)
    {
        
        $cats_id = explode(',',$ids);
        foreach($cats_id as $id){
            $cat = Client::findOrFail($id);
            $del = $cat->delete();
        }       
        if($del)
            connectify('success', 'Done',  __('site.deleted_successfully'));
        else
            connectify('error', 'Error', 'Somthing Wrong Please Try again later');
		return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/ClientOrdersController.php
<?php

namespace App\Http\Controllers\Dashboard;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Client;
use App\Models\Order;
use App\Models\Product;
use function foo\func;
class ClientOrdersController extends Controller
{
    public function create(Client $client)
    {
        $categories = Category::with('products')->get();
        $orders = $client->orders()->with('products')->paginate(5);
        return view('dashboard.clients.orders.create', compact( 'client', 'categories', 'orders'));

    }//end of create

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Client $client)
    {
        $request->validate([
            'products' => 'required|array',
        ]);

        $this->attach_order($request, $client);

        connectify('success', 'Done', __('site.added_successfully'));
		
        return redirect()->route('cp.orders.index');

    }//end of store

    public function edit(Client $client, Order $order)
    {
        $categories = Category::with('products')->get();
        $orders = $client->orders()->with('products')->paginate(5);
        return view('dashboard.clients.orders.edit', compact('client', 'order', 'categories', 'orders'));

    }//end of edit

    public function update(Request $request, Client $client, Order $order)
    {
        $request->validate([
            'products' => 'required|array',
        ]);

        $this->detach_order($order);

        $this->attach_order($request, $client);

        connectify('success', 'Done', __('site.updated_successfully'));
		return redirect()->route('cp.orders.index');

    }//end of update

    private function attach_order($request, $client)
    {
        $order = $client->orders()->create([]);

        $order->products()->attach($request->products);

        $total_price = 0;

        foreach ($request->products as $id => $quantity) {

            $product = Product::FindOrFail($id);
            $total_price += $product->sale_price * $quantity['quantity'];

            $product->update([
                'stock' => $product->stock - $quantity['quantity']
            ]);

        }//end of foreach

        $order->update([
            'total_price' => $total_price
        ]);

    }//end of attach order

    private function detach_order($order)
    {
        foreach ($order->products as $product) {

            $product->update([
                'stock' => $product->stock + $product->pivot->quantity
            ]);

        }//end of for each

        $order->delete();

    }//end of detach order
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Client;
use App\Models\Order;
use App\Models\Product;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index(){
        $categories_count = Category::count();
        $products_count = Product::count();
        $clients_count = Client::count();
        $users_count = User::whereRoleIs('admin')->count();

        $sales_data = Order::select(
            DB::raw('YEAR(created_at) as year'),
            DB::raw('MONTH(created_at) as month'),
            DB::raw('SUM(total_price) as sum')
        )->groupBy('month')->get();
        return view('dashboard.index',compact('categories_count', 'products_count', 'clients_count', 'users_count', 'sales_data'));
    }
}

app/Http/Controllers/Dashboard/OrderController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Order;
class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::orderBy('id','desc')->get();
        return view('dashboard.orders.index',compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }
    public function products(Order $order)
    {
        $products = $order->products;
        return view('dashboard.orders._products', compact('order', 'products'));

    }//end of products
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        foreach ($order->products as $product) {

            $product->update([
                'stock' => $product->stock + $product->pivot->quantity
            ]);

        }//end of for each

        $order->delete();
        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('dashboard.orders.index');
    
    }//end of order
}

resources/views/dashboard/categories/create.blade.php
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="addModalLabel">@lang('site.add')</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            @include('partials._errors')

            <form action="{{ route('cp.categories.store') }}" method="post" enctype="multipart/form-data">

                @csrf
                @foreach (config('translatable.locales') as $locale)
                            <div class="form-group">
                                <label>@lang('site.' . $locale . '.name')</label>
                                <input type="text" name="{{ $locale }}[name]" class="form-control" value="{{ old($locale . '.name') }}">
                            </div>
                 @endforeach

                <div class="form-group">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> @lang('site.add')</button>
                </div>

            </form><!-- end of form -->
        </div>
        
    </div>
    </div>
</div>

resources/views/dashboard/categories/edit.blade.php
<div class="modal fade" id="editModal_{{$cat->id}}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">@lang('site.edit') </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        @include('partials._errors')
        <div class="modal-body">
            <form action="{{ route('cp.categories.update', $cat->id) }}" method="post" enctype="multipart/form-data">
                <input name="_method" type="hidden" value="PATCH">
                @csrf
                @foreach (config('translatable.locales') as $locale)
                    <div class="form-group">
                        <label>@lang('site.' . $locale . '.name')</label>
                        <input type="text" name="{{ $locale }}[name]" class="form-control" value="{{ $cat->translate($locale)->name }}">
                    </div>
                @endforeach
                <div class="form-group">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> @lang('site.edit')</button>
                </div>

            </form><!-- end of form -->
        </div>
    </div>
    </div>
</div>

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layouts.app')
@section('content')
<section class="content-header">

        <h1>@lang('site.categories')</h1>

        <ol class="breadcrumb">
            <li><a href="{{ route('cp.index') }}"><i class="fa fa-dashboard"></i> @lang('site.dashboard')</a></li>
            <li class="active">@lang('site.categories')</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <div class="box">
              <div class="box-header">
                
              <h3 class="box-title">@lang('site.categories') : {{$cats->count()}}</h3>
              
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                @include('notify::messages')
                @if(auth()->user()->hasPermission('create_categories'))
                    <button type="button" class="btn btn-success float-left" data-toggle="modal" data-target="#addModal">
                        <i class="fa fa-plus"></i> @lang('site.add')
                    </button>
                @endif
                  <br><br>
                  <!-- Add Modal -->
                @include('dashboard.categories.create')
                @if($errors->any())
                    <div class="alert alert-danger"><p>{{$errors->first()}}</p></div>
                @endif   
                  <table class="table table-bordered data-table display select" id="categories_tbl">
                    <thead>
                        <tr>
                            <th class="no-sort"><input type="checkbox" class="selectAll" value="0"/></th>                                
                            <th>#</th>
                            <th>@lang('site.name')</th>
                            <th>@lang('site.products_count')</th>
                            <th>@lang('site.related_products')</th>
                            <th>@lang('site.action')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($cats as $key=>$cat)
                        <tr>
                            <td><input type="checkbox" name="all_Items[]" value="{{$cat->id}}" class="checkItem"></td>
                            <td>{{$key+1}}</td>
                            <td>{{ $cat->name }}</td>
                            <td>{{$cat->products()->count()}}</td>
                            <td><a href="{{ url('cp/catProducts/'.$cat->id) }}" class="btn btn-info btn-sm">@lang('site.related_products')</a></td>
                            <td>  
                                @if(auth()->user()->hasPermission('update_categories'))  
                                    <button class="btn btn-warning" data-toggle="modal" data-target="#editModal_{{$cat->id}}"><i class="fa fa-pencil"></i></button>
                                @endif
                                @if(auth()->user()->hasPermission('delete_categories'))
                                    <a href="{{url('cp/categories/delCat/'.$cat->id)}}" class="btn btn-danger delete-confirm"><i class="fa fa-trash"></i></a>
                                @endif
                                
                            </td>
                        </tr>
                            @if(auth()->user()->hasPermission('update_categories'))
                                @include('dashboard.categories.edit')
                            @endif
                        @endforeach

                    </tbody>
                 
                </table>
                @if(auth()->user()->hasPermission('delete_categories'))
                    <button class="btn btn-danger float-right confirm_all" type="submit" disabled>@lang('site.del_all')</button>
                @endif
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->
  
           
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
</section>
@push('scripts')
    
    <script>
        $(document).ready(function() {
            $('#categories_tbl').DataTable({
                "columnDefs": [ {
                    "targets": 'no-sort',
                    "orderable": false,
                    "order": []
                } ]
            } );
        });
        
       // confirm delete
        $('.delete-confirm').on('click', function (event) {
            event.preventDefault();
            const url = $(this).attr('href');
            swal({
                title: '@lang('site.confirm_delete')',
                text: '@lang('site.delete_msg')',
                icon: 'warning',
                buttons: ["@lang('site.no')", "@lang('site.yes')"],
            }).then(function(value) {
                if (value) {
                    window.location.href = url;
                }
            });
        });
        // enable check all items
        $('.selectAll').click(function () {    
            $(':checkbox.checkItem').prop('checked', this.checked);    
        }); 
        //show delete all button after check checkboxs
        $('.check:button').click(function () {
            var checked = !$(this).data('checked');
            $('input:checkbox').prop('checked', checked);
            $('.confirm_all').prop('disabled', !checked)
            $(this).data('checked', checked);
            if (checked == true) {
                $(this).val('Uncheck All');
            } else if (checked == false) {
                $(this).val('Check All');
            }
        });
        $('input:checkbox').change(function () {
            $('.confirm_all').prop('disabled', $('input:checkbox:checked').length == 0)
        })
        // confirm before delete All
        $('.confirm_all').click(function () {
            event.preventDefault();
            var ids = [];
            swal({
                title: '@lang('site.confirm_delete')',
                text: '@lang('site.delete_msg')',
                icon: 'warning',
                buttons: ["@lang('site.no')", "@lang('site.yes')"],
            }).then(function(value) {
                if (value) {
                    $.each($('.checkItem:checked'),function(){ 
                        if($(this).val() != 0)
                        ids.push($(this).val()); 
                    });
                    window.location.href = "{{url('cp/categoriesAll/delet_all_categories')}}"+'/'+ids;
                }
            });
        })
        
    </script>
@endpush   
@endsection